name: gleebit
favicon: null
layout_spectrum: 0.46099444665014744
typography_spectrum: 0.800817459821701
title: Gleebits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
